source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

use_frameworks!

target 'BBTest_Example' do
  pod 'BBTest', :path => '../'
  pod 'AFNetworking/Reachability'

end

target 'BBTest_Tests' do
  inherit! :search_paths
  
  pod 'Kiwi'
end
